Add binding of createObjectURL that takes a Blob.
tinymce/rescript-webapi pull request #106
Opened 2022-08-24 12:41 UTC by mvaled

The function 'URL.createObjectURL' can take File, Blob and MediaSource.  This PR simply adds a binding for Blob.

2022-08-25 08:38 UTC, spocke requested changes
- [ ] Add a changelog entry with the PR number

2022-08-25 08:41 UTC, mvaled commented
@spocke 

* [x]  Add a changelog entry with the PR number

2022-08-26 04:11 UTC, TheSpyder commented
Fixes #100

2022-08-26 04:13 UTC, TheSpyder approved these changes

2022-08-26 13:31 UTC, spocke approved these changes

2022-08-29 16:44 UTC, merged

2022-08-29 16:45 UTC, spocke commented
> @spocke @TheSpyder How is the process to merge this?

Merged it now. Sorry for the delay been a bit much at work.